export const styleTW = {
    gridDl: "grid grid-cols-[3em_1fr] text-2xl",
    title1: "text-4xl md:text-6xl font-normal",
    title2: "text-3xl md:text-4xl",
    title3: "text-2xl md:text-3xl",
    bageBlue: "text-xs inline-block py-2 px-2.5 leading-none text-center whitespace-nowrap align-baseline font-bold bg-blue-600 text-white rounded cursor-pointer",
    bageRed: "text-xs inline-block py-2 px-2.5 leading-none text-center whitespace-nowrap align-baseline font-bold bg-red-600 text-white rounded hover:bg-red-800",
    shadow: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline",
    container: "container mx-auto lg:max-w-[800px]",
    containerWide: 'container max-w-screen-lg mx-auto p-4 md:p-8 mt-5', 
    card: "mt-4 mb-2 p-6 md:p-8 shadow bg-white rounded-md",
    cardWhite: "bg-white shadow px-8 py-6 cursor-pointer border-b-2 pb-2",
    bottomBorder: "border-b-2",
    title1Gap: "md:my-4",
    cardsTwoRows: "grid grid-cols-1 md:grid-cols-2 gap-4 md:gap-8 mt-6 md:mt-8 lg:mt-10",
    exerciseWordCenter: "my-6 flex-1 flex items-center",
    exerciseCardSkeleton: "flex flex-col items-center m-auto max-w-xs w-full aspect-square",
    inputLine: 'border-b-2 w-full py-1 bg-transparent text-gray-700 leading-tight focus:outline-none focus:shadow-outline',
    btnDisable: "text-gray disabled:opacity-50 border-gray hover:border-gray",
    wordsMarker: {
        blue: 'text-blue-800 font-medium',
        yellow: 'text-yellow-800 font-medium',
        green: 'text-green-800 font-medium',
    }
}